/**
 * @author Richard S. Stansbury
 * @version 1.0, 2017-09-18
 *
 * Implementation of a singly linked list node.
 */
public class SLLNode<t> {


    //Class Variables
    public t info;
    public SLLNode<t> next;

    /**
     * Constructor for case where next node does not exist or is unknown.
     * @param info - info to be stored in node of type t.
     */
    public SLLNode(t info) {
        this.info = info;
        this.next = null;
    }

    /**
     * Constructor for case where next node exists and is known.
     * @param info - info to be stored in the node of type t
     * @param next - reference to the next node in the list
     */
    public SLLNode(t info, SLLNode<t> next) {
        this.info = info;
        this.next = next;
    }

    /**
     * @return a string generated by calling toString on the info stored within the node
     */
    public String toString() {
        return info.toString();
    }

    /**
     * Simple test case
     * @param args - arguments for test case (not used)
     */
    public static void main(String [] args) {

        SLLNode n1 = new SLLNode<>("Bob");
        n1 = new SLLNode<>("Alice", n1);

        SLLNode cur = n1;
        while(cur != null) {
            System.out.println(cur);
            cur = cur.next;
        }


    }

}
